"""ICAO Annex 14 Volume I profile metadata and capability declarations."""

CURRENT_RULESET_ID = "icao_annex14_vol1_current_ols"
CURRENT_DISPLAY_NAME = "ICAO Annex 14 Vol I - Current OLS"
CURRENT_DESIGN_STANDARD_DISPLAY_NAME = (
    "ICAO Annex 14 Vol I (9th Edition, Amendment 18)"
)
CURRENT_EDITION = "Annex 14 Volume I, Ninth Edition, Amendment 18"
CURRENT_STATUS = "stable"
CURRENT_DESCRIPTION = (
    "Production-supported current ICAO Annex 14 Volume I conventional OLS, "
    "applicable until 20 November 2030."
)
CURRENT_ALIASES = (
    "Annex 14",
    "ANNEX14",
    "annex14",
    "ICAO Annex 14",
    "icao_annex14",
    "annex14_current",
    "annex14_current_ols",
    "icao_annex14_vol1",
    "icao_annex14_vol1_current",
)

MODERNISED_RULESET_ID = "icao_annex14_vol1_modernised_ofs_oes"
MODERNISED_DISPLAY_NAME = "ICAO Annex 14 Vol I - Modernised OLS"
MODERNISED_EDITION = "Annex 14 Volume I modernised OFS/OES"
MODERNISED_STATUS = "stable"
MODERNISED_DESCRIPTION = (
    "Future ICAO Annex 14 Volume I protected-airspace model using OFS/OES and ADG, "
    "not enforceable until 21 November 2030."
)
MODERNISED_ALIASES = (
    "Annex 14 Modernised",
    "Annex 14 Modernized",
    "Annex 14 OFS/OES",
    "ICAO Annex 14 Modernised",
    "icao_annex14_modernised",
    "icao_annex14_modernized",
    "icao_annex14_ofs_oes",
    "icao_annex14_vol1_modernised",
)
MODERNISED_ASSUMPTIONS = (
    "Runway-end operation applicability is derived automatically from the "
    "declared runway type and take-off availability.",
    "Approach operations are assumed to be aligned straight-in operations; "
    "non-precision ends establish the standard straight-in instrument OES and "
    "precision ends establish the standard precision-approach OES.",
    "Instrument-departure OES is established automatically for instrument "
    "runway ends where take-off is available.",
    "Take-off-climb OES uses the conservative above-5,700 kg table when no "
    "aircraft mass is supplied.",
    "ARC letter F automatically applies the Code F case without qualifying "
    "digital go-around guidance.",
    "The modernised OFS strip is resolved automatically from the selected "
    "aerodrome design ruleset and is held identical across both sides of an "
    "OLS comparison.",
    "Blank approach-slope and obstacle-clearance-height adjustments use the "
    "unadjusted standard table dimensions.",
    "The ADG horizontal OES is included by default, independently of whether "
    "a circling or visual-circuit procedure is declared.",
)
MODERNISED_LIMITATIONS = (
    "Circling and visual-circuit procedure-specific geometry beyond the "
    "default ADG horizontal OES is not generated.",
    "Curved, offset, and user-defined specific OES are not generated by the "
    "automatic workflow.",
    "Procedure-specific reduced approach slopes and OCH-driven length "
    "extensions are not modelled.",
    "The light-aircraft take-off-climb case at or below 5,700 kg is not "
    "selected by the automatic workflow.",
    "Manual or irregular approved strip geometry cannot be entered from the "
    "runway tab; the selected design-ruleset strip is used.",
    "Physical aerodrome design, declared-distance design, markings, and "
    "lighting remain outside this protected-airspace profile.",
    "The model is future-applicable from 21 November 2030 and is not currently "
    "enforceable.",
)

RULESET_ID = MODERNISED_RULESET_ID
DISPLAY_NAME = MODERNISED_DISPLAY_NAME
EDITION = "Annex 14 Volume I"
STATUS = "stable"
DESCRIPTION = MODERNISED_DESCRIPTION
ALIASES = MODERNISED_ALIASES

CAPABILITY_STATUS_BY_KEY = {
    "classification.runway_type_mapping": "supported",
    "classification.reference_code": "supported",
    "classification.design_group": "supported",
    "physical.pavement": "unsupported",
    "physical.shoulder": "unsupported",
    "physical.strip": "unsupported",
    "physical.resa": "unsupported",
    "physical.clearway": "unsupported",
    "physical.stopway": "unsupported",
    "physical.taxiway_separation": "unsupported",
    "physical.parallel_runway_separation": "unsupported",
    "ols.airport_wide": "supported",
    "ols.obstacle_free_surfaces": "supported",
    "ols.runway_approach": "supported",
    "ols.takeoff_climb": "unsupported",
    "ols.ofz": "supported",
    "ols.controlling_lower_envelope": "supported",
    "oes.airport_wide": "supported",
    "oes.design_group_driven": "supported",
    "oes.horizontal": "supported",
    "oes.straight_in_instrument_approach": "supported",
    "oes.precision_approach": "supported",
    "oes.instrument_departure": "supported",
    "oes.take_off_climb": "supported",
    "oes.specific": "unsupported",
    "obstacle_limitation.requirements": "supported",
    "obstacle_limitation.surface_establishment": "supported",
    "markings.runway": "unsupported",
    "lighting.runway": "unsupported",
    "lighting.approach": "unsupported",
    "declared_distances.calculated": "unsupported",
}

CURRENT_CAPABILITY_STATUS_BY_KEY = {
    **CAPABILITY_STATUS_BY_KEY,
    "classification.design_group": "unsupported",
    "physical.strip": "supported",
    "physical.clearway": "supported",
    "physical.stopway": "supported",
    "ols.airport_wide": "supported",
    "ols.obstacle_free_surfaces": "unsupported",
    "ols.runway_approach": "supported",
    "ols.takeoff_climb": "supported",
    "ols.ofz": "supported",
    "ols.controlling_lower_envelope": "supported",
    "oes.airport_wide": "unsupported",
    "oes.design_group_driven": "unsupported",
    "oes.horizontal": "unsupported",
    "oes.straight_in_instrument_approach": "unsupported",
    "oes.precision_approach": "unsupported",
    "oes.instrument_departure": "unsupported",
    "oes.take_off_climb": "unsupported",
    "obstacle_limitation.requirements": "unsupported",
    "obstacle_limitation.surface_establishment": "unsupported",
}

MODERNISED_CAPABILITY_STATUS_BY_KEY = CAPABILITY_STATUS_BY_KEY

__all__ = [
    "CURRENT_RULESET_ID",
    "CURRENT_DISPLAY_NAME",
    "CURRENT_DESIGN_STANDARD_DISPLAY_NAME",
    "CURRENT_EDITION",
    "CURRENT_STATUS",
    "CURRENT_DESCRIPTION",
    "CURRENT_ALIASES",
    "CURRENT_CAPABILITY_STATUS_BY_KEY",
    "MODERNISED_RULESET_ID",
    "MODERNISED_DISPLAY_NAME",
    "MODERNISED_EDITION",
    "MODERNISED_STATUS",
    "MODERNISED_DESCRIPTION",
    "MODERNISED_ALIASES",
    "MODERNISED_ASSUMPTIONS",
    "MODERNISED_LIMITATIONS",
    "MODERNISED_CAPABILITY_STATUS_BY_KEY",
    "RULESET_ID",
    "DISPLAY_NAME",
    "EDITION",
    "STATUS",
    "DESCRIPTION",
    "ALIASES",
    "CAPABILITY_STATUS_BY_KEY",
]
