# -*- coding: utf-8 -*-
"""OLS guideline generation defaults."""

CONICAL_CONTOUR_INTERVAL = 10.0
APPROACH_CONTOUR_INTERVAL = 10.0
TOCS_CONTOUR_INTERVAL = 10.0
TRANSITIONAL_CONTOUR_INTERVAL = 10.0

__all__ = [
    "CONICAL_CONTOUR_INTERVAL",
    "APPROACH_CONTOUR_INTERVAL",
    "TOCS_CONTOUR_INTERVAL",
    "TRANSITIONAL_CONTOUR_INTERVAL",
]
