# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SafeguardingBuilder
                                 A QGIS plugin
 Generates NASF safeguarding layers based on a set of runway threshold coordinates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-31
        copyright            : (C) 2025 by Cam Todd
        email                : cam.todd@to70.com.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SafeguardingBuilder class from file SafeguardingBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .safeguarding_builder import SafeguardingBuilder
    return SafeguardingBuilder(iface)
