# -*- coding: utf-8 -*-
"""Generated layer tree labels for Safeguarding Builder outputs."""

REFERENCE_DATA = "01 Aerodrome Reference Data"
LEGACY_REFERENCE_DATA = "01 Reference Data"
AERODROME_INFRASTRUCTURE = "02 Runway Infrastructure"
RUNWAY_PROTECTION_AND_SEPARATION = "03 Runway Protection and Safeguarding"
PROTECTED_AIRSPACE = "04 Obstacle Limitation Surfaces"
CNS_TECHNICAL_SAFEGUARDING = "05 CNS / Technical Facilities"
AIRFIELD_GROUND_LIGHTING = "06 Airfield Ground Lighting"
EXTERNAL_SAFEGUARDING = "07 External Safeguarding"
TERRAIN_ANALYSIS = "08 Terrain Analysis"
IMPORTED_AIRPORT_MAP = "09 Imported Airport Map"

LEGACY_AERODROME_INFRASTRUCTURE = "02 Aerodrome Infrastructure"
LEGACY_RUNWAY_PROTECTION = "03 Runway Protection and Separation"
LEGACY_CNS_TECHNICAL_SAFEGUARDING = "05 CNS / Technical Safeguarding"
LEGACY_EXTERNAL_SAFEGUARDING = "06 External Safeguarding"

RUNWAY_CENTRE_LINES = "Runway Centrelines"
CNS_TECHNICAL_FACILITIES = "CNS / Technical Facilities"
METEOROLOGICAL_STATION = "Meteorological Instrument Station"

MARKINGS = "Markings"
PHYSICAL_GEOMETRY = "Physical Geometry"

RUNWAY_PROTECTION_AREAS = "Runway Protection Areas"
SPECIALISED_RUNWAY_SAFEGUARDING = "Specialised Runway Safeguarding"

OLS_SURFACES = "OLS Surfaces"
AIRPORT_WIDE_OLS = "Airport-wide OLS"
RUNWAY_APPROACH_AND_TAKE_OFF = "Runway Approach And Take-off"
OBSTACLE_FREE_ZONE = "Obstacle Free Zone"
CONTROLLING_OLS_SURFACES = "Controlling OLS Surfaces"
CONTROLLING_CONTOURS = "Controlling Contours"

PRIMARY_SURFACES = "Primary Surfaces"
SECONDARY_SURFACES = "Secondary Surfaces"
CONTROLLING_SURFACES = "Controlling Surfaces"

SECTION_ORDER = [
    REFERENCE_DATA,
    AERODROME_INFRASTRUCTURE,
    RUNWAY_PROTECTION_AND_SEPARATION,
    PROTECTED_AIRSPACE,
    CNS_TECHNICAL_SAFEGUARDING,
    AIRFIELD_GROUND_LIGHTING,
    EXTERNAL_SAFEGUARDING,
    TERRAIN_ANALYSIS,
    IMPORTED_AIRPORT_MAP,
]

__all__ = [
    "AERODROME_INFRASTRUCTURE",
    "AIRFIELD_GROUND_LIGHTING",
    "AIRPORT_WIDE_OLS",
    "CNS_TECHNICAL_FACILITIES",
    "CNS_TECHNICAL_SAFEGUARDING",
    "CONTROLLING_CONTOURS",
    "CONTROLLING_OLS_SURFACES",
    "CONTROLLING_SURFACES",
    "EXTERNAL_SAFEGUARDING",
    "IMPORTED_AIRPORT_MAP",
    "LEGACY_AERODROME_INFRASTRUCTURE",
    "LEGACY_CNS_TECHNICAL_SAFEGUARDING",
    "LEGACY_EXTERNAL_SAFEGUARDING",
    "LEGACY_REFERENCE_DATA",
    "LEGACY_RUNWAY_PROTECTION",
    "MARKINGS",
    "METEOROLOGICAL_STATION",
    "OBSTACLE_FREE_ZONE",
    "OLS_SURFACES",
    "PHYSICAL_GEOMETRY",
    "PRIMARY_SURFACES",
    "PROTECTED_AIRSPACE",
    "REFERENCE_DATA",
    "RUNWAY_APPROACH_AND_TAKE_OFF",
    "RUNWAY_CENTRE_LINES",
    "RUNWAY_PROTECTION_AND_SEPARATION",
    "RUNWAY_PROTECTION_AREAS",
    "SECONDARY_SURFACES",
    "SECTION_ORDER",
    "SPECIALISED_RUNWAY_SAFEGUARDING",
    "TERRAIN_ANALYSIS",
]
