# -*- coding: utf-8 -*-
"""Generated layer tree labels for Safeguarding Builder outputs."""

REFERENCE_DATA = "01 Reference Data"
AERODROME_INFRASTRUCTURE = "02 Aerodrome Infrastructure"
RUNWAY_PROTECTION_AND_SEPARATION = "03 Runway Protection and Separation"
PROTECTED_AIRSPACE = "04 Protected Airspace"
EXTERNAL_SAFEGUARDING = "05 External Safeguarding"
DEBUG_DEVELOPMENT = "99 Debug / Development"

RUNWAY_CENTRE_LINES = "Runway Centrelines"
CNS_TECHNICAL_FACILITIES = "CNS / Technical Facilities"
METEOROLOGICAL_STATION = "Meteorological Instrument Station"

AIRFIELD_GROUND_LIGHTING = "Airfield Ground Lighting"
MARKINGS = "Markings"
PHYSICAL_GEOMETRY = "Physical Geometry"

RUNWAY_PROTECTION_AREAS = "Runway Protection Areas"
SPECIALISED_RUNWAY_SAFEGUARDING = "Specialised Runway Safeguarding"

OLS_SURFACES = "OLS Surfaces"
AIRPORT_WIDE_OLS = "Airport-wide OLS"
RUNWAY_APPROACH_AND_TAKE_OFF = "Runway Approach And Take-off"
OBSTACLE_FREE_ZONE = "Obstacle Free Zone"
CONTROLLING_OLS_SURFACES = "Controlling OLS Surfaces"
CONTROLLING_CONTOURS = "Controlling Contours"

SECTION_ORDER = [
    REFERENCE_DATA,
    AERODROME_INFRASTRUCTURE,
    RUNWAY_PROTECTION_AND_SEPARATION,
    PROTECTED_AIRSPACE,
    EXTERNAL_SAFEGUARDING,
    DEBUG_DEVELOPMENT,
]

__all__ = [
    "AERODROME_INFRASTRUCTURE",
    "AIRFIELD_GROUND_LIGHTING",
    "AIRPORT_WIDE_OLS",
    "CNS_TECHNICAL_FACILITIES",
    "CONTROLLING_CONTOURS",
    "CONTROLLING_OLS_SURFACES",
    "DEBUG_DEVELOPMENT",
    "EXTERNAL_SAFEGUARDING",
    "MARKINGS",
    "METEOROLOGICAL_STATION",
    "OBSTACLE_FREE_ZONE",
    "OLS_SURFACES",
    "PHYSICAL_GEOMETRY",
    "PROTECTED_AIRSPACE",
    "REFERENCE_DATA",
    "RUNWAY_APPROACH_AND_TAKE_OFF",
    "RUNWAY_CENTRE_LINES",
    "RUNWAY_PROTECTION_AND_SEPARATION",
    "RUNWAY_PROTECTION_AREAS",
    "SECTION_ORDER",
    "SPECIALISED_RUNWAY_SAFEGUARDING",
]
