# -*- coding: utf-8 -*-
"""Default QML style mapping for generated safeguarding layers."""

DEFAULT_STYLE_MAP = {
    "ARP": "arp_point.qml",
    "Runway Centreline": "rwy_centreline_line.qml",
    "AGL Light": "agl_lights.qml",
    "MET Station Location": "default_point.qml",
    "MET Instrument Enclosure": "default_zone_polygon.qml",
    "MET Buffer Zone": "default_zone_polygon.qml",
    "MET Obstacle Buffer Zone": "default_zone_polygon.qml",
    "Runway Pavement": "physical_runway.qml",
    "PreThreshold Runway": "physical_prethreshold_runway.qml",
    "PreThreshold Area": "physical_prethreshold_area.qml",
    "Runway Marking White": "runway_marking_white.qml",
    "Runway Marking Yellow": "runway_marking_yellow.qml",
    "Runway Designation Text": "runway_designation_text.qml",
    "Runway Shoulders": "physical_runway_shoulder.qml",
    "Runway Graded Strips": "physical_graded_strips.qml",
    "Runway Overall Strips": "physical_overall_strips.qml",
    "Runway Strip Flyover Area": "default_zone_polygon.qml",
    "Runway End Safety Areas (RESA)": "physical_resa.qml",
    "Stopways": "default_zone_polygon.qml",
    "Clearways": "default_zone_polygon.qml",
    "RAOA": "default_zone_polygon.qml",
    "Taxiway Separation Line": "twy_separation_line.qml",
    "Parallel Runway Standards Line": "default_ols_line.qml",
    "WSZ Runway": "nasf_windshear.qml",
    "WMZ A": "nasf_wildlife_a.qml",
    "WMZ B": "nasf_wildlife_b.qml",
    "WMZ C": "nasf_wildlife_c.qml",
    "Wind Turbine Assessment Zone": "nasf_wind_turbine.qml",
    "UK Wildlife Consultation": "nasf_wildlife_c.qml",
    "UK Wind Turbine Consultation": "default_zone_polygon.qml",
    "UK PSRZ": "default_zone_polygon.qml",
    "UK PSCZ": "default_zone_polygon.qml",
    "LCZ A": "nasf_lighting_a.qml",
    "LCZ B": "nasf_lighting_b.qml",
    "LCZ C": "nasf_lighting_c.qml",
    "LCZ D": "nasf_lighting_d.qml",
    "LCZ Area": "nasf_lighting_area.qml",
    "OLS Approach": "harmonised_ols_surfaces.qml",
    "OLS Approach Contour": "harmonised_ols_contours.qml",
    "OLS Inner Approach": "harmonised_ols_surfaces.qml",
    "OLS Inner Transitional": "harmonised_ols_surfaces.qml",
    "OLS Baulked Landing": "harmonised_ols_surfaces.qml",
    "OLS OFZ Contour": "harmonised_ols_contours.qml",
    "OLS TOCS": "harmonised_ols_surfaces.qml",
    "OLS TOCS Contour": "harmonised_ols_contours.qml",
    "OLS IHS": "harmonised_ols_surfaces.qml",
    "OLS Transitional": "harmonised_ols_surfaces.qml",
    "OLS Transitional Contour": "harmonised_ols_contours.qml",
    "OLS Conical": "harmonised_ols_surfaces.qml",
    "OLS Conical Contour": "harmonised_ols_contours.qml",
    "OLS OHS": "harmonised_ols_surfaces.qml",
    "OLS Controlling Planar Region": "harmonised_ols_surfaces.qml",
    "OLS Controlling Contour": "harmonised_ols_contours.qml",
    "Annex 14 OFS Surface": "annex14_ofs_surfaces.qml",
    "Annex 14 OES Surface": "annex14_oes_surfaces.qml",
    "Annex 14 OFS Contour": "annex14_ofs_contours.qml",
    "Annex 14 OES Contour": "annex14_oes_contours.qml",
    "Annex 14 Controlling OFS": "annex14_ofs_surfaces.qml",
    "Annex 14 Controlling OES": "annex14_oes_surfaces.qml",
    "Annex 14 Candidate OFS": "annex14_ofs_surfaces.qml",
    "Annex 14 Candidate OES": "annex14_oes_surfaces.qml",
    "Annex 14 Transition OFS": "annex14_ofs_contours.qml",
    "Annex 14 Transition OES": "annex14_oes_contours.qml",
    "OLS Modernisation Gain": "default_ols_polygon.qml",
    "OLS Modernisation Loss": "default_ols_polygon.qml",
    "OLS Modernisation No Change": "default_ols_polygon.qml",
    "OLS Modernisation No Future Overlay": "default_ols_polygon.qml",
    "OLS Modernisation Baseline Wireframe": "default_ols_polygon.qml",
    "OLS Modernisation Future Wireframe": "default_ols_polygon.qml",
    "OLS Modernisation Transition": "default_ols_line.qml",
    "OLS Modernisation Change Contour": "default_ols_line.qml",
    "CNS Circle Zone": "nasf_cns_circle.qml",
    "CNS Donut Zone": "nasf_cns_donut.qml",
    "Default CNS": "nasf_cns_default.qml",
    "CNS Contour": "nasf_cns_contours.qml",
    "CNS Source Facility": "cns_source_facility.qml",
    "PSA Runway": "nasf_public_safety_area.qml",
    "Default Polygon": "default_zone_polygon.qml",
    "Default Line": "default_ols_line.qml",
    "Default Point": "default_point.qml",
}
