# -*- coding: utf-8 -*-
"""Default QML style mapping for generated safeguarding layers."""

DEFAULT_STYLE_MAP = {
    "ARP": "arp_point.qml",
    "Runway Centreline": "rwy_centreline_line.qml",
    "AGL Light": "agl_lights.qml",
    "MET Station Location": "default_point.qml",
    "MET Instrument Enclosure": "default_zone_polygon.qml",
    "MET Buffer Zone": "default_zone_polygon.qml",
    "MET Obstacle Buffer Zone": "default_zone_polygon.qml",
    "Runway Pavement": "physical_runway.qml",
    "PreThreshold Runway": "physical_prethreshold_runway.qml",
    "PreThreshold Area": "physical_prethreshold_area.qml",
    "Runway Marking White": "runway_marking_white.qml",
    "Runway Marking Yellow": "runway_marking_yellow.qml",
    "Runway Designation Text": "runway_designation_text.qml",
    "Runway Shoulders": "physical_runway_shoulder.qml",
    "Runway Graded Strips": "physical_graded_strips.qml",
    "Runway Overall Strips": "physical_overall_strips.qml",
    "Runway Strip Flyover Area": "default_zone_polygon.qml",
    "Runway End Safety Areas (RESA)": "physical_resa.qml",
    "Stopways": "default_zone_polygon.qml",
    "Clearways": "default_zone_polygon.qml",
    "RAOA": "default_zone_polygon.qml",
    "Taxiway Separation Line": "twy_separation_line.qml",
    "WSZ Runway": "guideline_b_wsz.qml",
    "WMZ A": "default_zone_polygon.qml",
    "WMZ B": "default_zone_polygon.qml",
    "WMZ C": "default_zone_polygon.qml",
    "Wind Turbine Assessment Zone": "default_zone_polygon.qml",
    "LCZ A": "default_zone_polygon.qml",
    "LCZ B": "default_zone_polygon.qml",
    "LCZ C": "default_zone_polygon.qml",
    "LCZ D": "default_zone_polygon.qml",
    "OLS Approach": "ols_approach_polygon.qml",
    "OLS Approach Contour": "ols_approach_contours.qml",
    "OLS Inner Approach": "default_ofz_polygon.qml",
    "OLS Inner Transitional": "default_ofz_polygon.qml",
    "OLS Baulked Landing": "default_ofz_polygon.qml",
    "OLS TOCS": "ols_tocs_polygon.qml",
    "OLS TOCS Contour": "ols_tocs_contours.qml",
    "OLS IHS": "default_ols_polygon.qml",
    "OLS Transitional": "default_ols_polygon.qml",
    "OLS Transitional Contour": "ols_transitional_contours.qml",
    "OLS Conical": "default_ols_polygon.qml",
    "OLS Conical Contour": "ols_conical_contours.qml",
    "OLS OHS": "default_ols_polygon.qml",
    "OLS Controlling Planar Region": "test_ols_polygon.qml",
    "CNS Circle Zone": "default_cns_zone_polygon.qml",
    "CNS Donut Zone": "default_cns_zone_polygon.qml",
    "Default CNS": "default_cns_zone_polygon.qml",
    "PSA Runway": "guideline_i_psa.qml",
    "Default Polygon": "default_zone_polygon.qml",
    "Default Line": "default_ols_line.qml",
    "Default Point": "default_point.qml",
}
